web/interviews/urls.py
# coding: utf-8

from django.conf.urls import url
from . import views

app_name = 'interviews'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^search$', views.search, name='search'),
    url(r'^log$', views.log, name='log'),
    # url(r'^search-(?P<current_page_num>[0-9]+)$', views.search, name='search'),
]

web/web_django/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^', include('interviews.urls')),
    url(r'^admin/', admin.site.urls),
]

web/interviews/models.py
from __future__ import unicode_literals

from django.db import models


# Create your models here.
from django.utils import timezone


class Post(models.Model):
    title = models.TextField()
    link = models.TextField()
    create_time = models.DateTimeField(default=timezone.now)
    source = models.CharField(max_length=200)
    source_link = models.TextField()
    description = models.TextField()
    tag = models.CharField(max_length=200)

    def __str__(self):
        return self.source + " : " + self.title + " TAG: " + self.tag


class Statistic(models.Model):
    total_post_num = models.IntegerField(default=0)
    fuck = models.CharField(max_length=100, default='fuck')


# class Source(models.Model):
#     source_name = models.CharField(max_length=200)
#     source_link = models.TextField()

web/interviews/views.py
# coding: utf-8
import os

from django.db.models import Q
from django.http import Http404
from django.shortcuts import render, get_object_or_404

from models import Post
import chardet
import random
import re

from django.utils.http import urlunquote, urlquote

# tips displayed in search placeholder
tips = ("搜索关键词，例如：Google",
        "空格隔开关键词,例如:Amazon onsite",
        )

# Tags for keyword transfer while searching
# All the contents will be in lowercase
TAGS = {
    # Companies
    'Google': ('google', 'googl', 'g家', '谷歌'),
    'Amazon': ('amazon', 'a家', '亚麻', '亚马逊', '亚玛逊'),
    'LinkedIn': ('linkedin', 'linkin', 'l家', '领英'),
    'Facebook': ('fb', 'facebook', '脸书', 'f家'),
    'Microsoft': ('microsoft', 'm家', '微软'),
    'Airbnb': ('airbnb',),
    'Uber': ('uber', '优步'),

    # Other Keywords
    'Onsite': ('onsite',),
    'Resume': ('resume', '简历'),
    'OA': ('oa', '在线测试'),
    'Intern': ('intern', 'internship', '实习'),
}

def index(request):
    all_posts = Post.objects.all()

    content_newest_models = all_posts.order_by("-create_time")[:10]
    content_newest = [(models, models.create_time.strftime("%b %d"))
                      for models in content_newest_models]


    board_names = ("Google",
                   "Amazon",
                   "Facebook",
                   "Linkedin",
                   "Uber",
                   "Microsoft",
                   # "Airbnb",
                   "Onsite",
                   "Intern")

    boards = []
    for board_name in board_names:
        args = (Q(tag__icontains=board_name),)
        board_content_models = all_posts.filter(*args).order_by("-create_time")[:10]
        board_content = [(models, models.create_time.strftime("%b %d")) for models in board_content_models]
        boards += [(board_name, board_content)]

    # print all_posts[0].create_time.strftime("%d %b")

    content = {
        "total_num": len(all_posts),
        "content_newest": content_newest,
        "boards": boards,
        "tips": random.choice(tips)
    }
    return render(request, 'interviews/index.html', content)


def search(request):

    # get the GET params from request
    if request.GET.get('pn'):
        current_page_id = request.GET.get('pn')
    else:
        current_page_id = 1
    current_page_id = int(current_page_id)

    # set the results you wanna to show on each page
    result_num_each_page = 10

    # get all required posts from db
    keyword = ""
    if request.GET.get('wd') and request.GET.get('wd').encode('utf-8') != "":
        keyword = request.GET.get('wd').encode('utf-8')
        wds = keyword.split(" ")
        wds = filter(None, wds)
        # transfer specific kw to tags
        for i in range(0, len(wds)):
            for (key, values) in TAGS.items():
                if wds[i] in values:
                    wds[i] = key
                    break

        print wds

        # search using multiple keywords
        args = ()
        for wd in wds:
            args += (Q(title__icontains=wd) |
                     Q(description__icontains=wd) |
                     Q(tag__icontains=wd),)

        all_posts = Post.objects.filter(*args)

        # Sorting Algorithm

        # End of Sorting
    else:
        all_posts = Post.objects.all()
    # print chardet.detect(request.GET.get('wd').encode('utf-8'))

    # get total nums of results and calculate total page nums
    result_num = len(all_posts)
    total_page_num = result_num / result_num_each_page + 1

    # if the required page id is invalid, return 404 page
    if current_page_id > total_page_num or current_page_id <= 0:
        raise Http404("No Such Page!")

    # deal with next_page, prev_page
    # False if need to be disabled, otherwise the target url
    prev_page = False
    next_page = False
    if current_page_id > 1:
        url = "/search?pn=%d&wd=%s" % (current_page_id - 1, urlquote(keyword))
        prev_page = url
    if current_page_id < total_page_num:
        url = "/search?pn=%d&wd=%s" % (current_page_id + 1, urlquote(keyword))
        next_page = url

    # deal with pages
    # False if no need to show page
    # otherwise make it a list of (id of page, url of page)
    pages = []
    if total_page_num == 1:
        pages = False
    elif total_page_num <= 5:
        for i in range(1, total_page_num + 1):
            url = "/search?pn=%d&wd=%s" % (i, urlquote(keyword))
            pages += [(i, url)]
            # print url
    else:
        start_page = max(1, current_page_id - 2)
        end_page = min(total_page_num, current_page_id + 2)
        if end_page - start_page + 1 < 5:
            if end_page == total_page_num:
                start_page = end_page - 4

        for i in range(start_page, start_page + 5):
            url = "/search?pn=%d&wd=%s" % (i, urlquote(keyword))
            pages += [(i, url)]

    # calculate the items we are going to show
    # put the items and their tags in the list [items]
    start_id = (current_page_id - 1) * result_num_each_page
    end_id = start_id + result_num_each_page
    item_list = all_posts.order_by('-create_time')[start_id : end_id]
    items = []
    for item in item_list:
        tags = [n for n in item.tag.split(' ') if n.strip()]
        items += [[item, tags]]

    # calculate the truely item start and end id
    start_id += 1
    end_id = start_id + len(item_list) - 1

    content = {
        "items": items,
        "result_num": result_num,
        "pages": pages,
        "page_num": total_page_num,
        "current_page_num": current_page_id,
        "prev_page": prev_page,
        "next_page": next_page,
        "item_start_id": start_id,
        "item_end_id": end_id,
        "search_keyword": keyword,
        "tips": random.choice(tips),
    }

    return render(request, 'interviews/search.html', content)


def log(request):
    # logFile = open('/code/web_scrapy/logs/scrapy.log', 'r')
    logFile = open('/code/web_scrapy/logs/shell.log', 'r')

    # logFile.seek(-10000, os.SEEK_END)
    lines = logFile.readlines()
    # for row in lines[::-1]:

    content = {
        'lines': lines[::-1]
    }
    return render(request, 'interviews/log.html', content)

web/interviews/templates/interviews/index.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>面经搜索</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/index.css' %}" rel="stylesheet">

{#    <link href="static_global/bootstrap/css/bootstrap.css" rel="stylesheet">#}
{#    <link href="static_global/css/font-awesome.min.css" rel="stylesheet">#}
{#    <link href="static/css/index.css" rel="stylesheet">#}

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/index.js' %}"></script>


    <!--[if lt IE 9]>
        <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
        <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

    <header class="site-header jumbotron">
        <div class="site-nav">
            <a href="#about">About</a>
        </div>
        <div class="container">
            <div class="row">
                <div class="col-xs-12">
                    <h1>面 经 搜 索</h1>
                    <p>北美 IT 岗位面试经验搜索<br>
                        <span class="package-amount">已收录了 <strong>{{ total_num }}</strong> 个面经</span>
                    </p>
                    <form id="form-search" role="search" method="get" action="{% url 'interviews:search'%}">
                        <div class="form-group">
                            <input type="text" name="wd" class="form-control search clearable" placeholder="{{ tips }}">
                            <i class="fa fa-search" id="i-search"></i>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </header>

    <div class="container">
        <div class="row">

            <div class="board col-xs-12 col-md-12 col-lg-6">
                <div class="board-header">
                    <span>最新面经</span>
                    <a href="{% url 'interviews:search'%}">More</a>
                </div>

                <div class="board-content">
                    {% for model, time in content_newest %}
                    <div>
                        <span class="board-content-time">{{ time }}</span>
                        <div class="board-content-title">
                            <a href="{{ model.link }}" target="_blank">{{ model.title }}</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>

            {% for board_name, board_content in boards %}
            <div class="board col-xs-12 col-md-6 col-lg-3">
                <div class="board-header">
                    <span>{{ board_name }}</span>
                    <a href="javascript:httpGet('{% url 'interviews:search'%}', '{{ board_name }}')">More</a>
                </div>

                <div class="board-content">
                    {% for model, time in board_content %}
                    <div>
                        <span class="board-content-time">{{ time }}</span>
                        <div class="board-content-title">
                            <a href="{{ model.link }}" target="_blank">{{ model.title }}</a>
                        </div>
                    </div>
                    {% endfor %}
                </div>

            </div>
            {% endfor %}

        </div> <!-- / row -->
    </div>

    <footer id="footer" class="footer ">
        <div class="footer-about " id="about">
            <h4>关于 本网站</h4>
            <p>本网站尚在开发中</p>
            <p>有任何建议欢迎反馈到邮件：###@###.com</p>
        </div>
    </footer>

</body>

</html>

web/interviews/templates/interviews/log.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Log</title>
</head>
<body>
    <div>
        {% for line in lines %}
        <p>{{ line }}</p>
        {% endfor %}
    </div>

</body>
</html>

web/interviews/templates/interviews/newest.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Newest</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/newest.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/newest.js' %}"></script>


    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div class="navbar navbar-inverse navbar-extra navbar-fixed-top">
    <div class="container">

        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target=".navbar-collapse">
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
        </div>

        <div class="navbar-collapse collapse">
            <ul class="nav navbar-nav">
                <li id="home">
                    <a href="{% url 'interviews:index' %}">Home</a>
                </li>

                <li class="active" id="newest">
                    <a href="newest/"><font color="orange">Newest</font></a>
                </li>

                <li id="flag">
                    <a href="flag/">FLAG</a>
                </li>
                <!-- TODO: not hard code -->
            </ul>
        </div><!--/.navbar-collapse -->
    </div>
</div>

<div id="wrapper">
<!--<header class="site-header">-->
    <div class="container search-bar">
        <div class="row">
            <div class="col-xs-7">
                <form class="" role="search">
                    <div class="form-group">
                        <input type="text" class="form-control search clearable" placeholder="搜索关键词，例如：Google Tree">
                        <i class="fa fa-search"></i>
                    </div>
                </form>
            </div>

            <div class="col-xs-3">
                <!--<div class="form-group">-->
                    <!--<select class="form-control">-->
                        <!--<option>Choose one filter</option>-->
                        <!--<option>Facebook</option>-->
                        <!--<option>Linkedin</option>-->
                        <!--<option>Amazon</option>-->
                        <!--<option>Google</option>-->
                        <!--<option>Others</option>-->
                    <!--</select>-->
                <!--</div>-->
            </div>
        </div>
        <div class="row">
            <div class="col-xs-12">
                <p>共为您找到{{ result_num }}个结果</p>
            </div>
        </div>
    </div>
<!--</header>-->

    <div class="container">
        <div class="row results">
            {% for item in items %}
            <div class="col-xs-7 content-wrapper">
                <div class="content">
                    <a name="{{ forloop.counter }}" class="content-title" href="{{ item.link }}" target="_blank">{{ item.title }}</a>
                    <p>
                        <span class="content-time">{{ item.create_time }} - </span>
                        {% if item.description|length > 200 %}
                        <span hidden class="content-desc-all">{{ item.description}}</span>
                        <span class="content-desc-partial">{{ item.description|slice:"200" }} ...</span>
                        <a title="{{ forloop.counter }}" href="javascript:void(0);" class="toggle-expand" onclick="content_toggle(this)">Show All</a>
                        {% else %}
                        <span class="content-desc">{{ item.description }}</span>
                        {% endif %}
                    </p>
                    <div class="content-footer">
                        <a class="content-source" href="{{ item.source_link }}" target="_blank">{{ item.source }}</a>
                        &nbsp;&nbsp;&nbsp;
                        <a class="content-source" href="{{ item.link }}" target="_blank">查看原帖</a>
                    </div>
                </div>
            </div>
            {% endfor %}
        </div> <!-- / row -->
    </div>


<div id="page">

    <a href="#" class="n">&lt;上一页</a>

    <strong>
        <span class="pc">1</span>
    </strong>

    <a href="">
        <span class="pc">2</span>
    </a>

    <a href="" class="n">下一页&gt;</a>
</div>

</div>



</body>

</html>

web/interviews/templates/interviews/search.html
<!DOCTYPE html>

<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <title>Search</title>
    <meta name="description" content="">
    <meta name="keywords" content="">
    <meta name="author" content="">

    {% load staticfiles %}
    <link href="{% static 'bootstrap/css/bootstrap.css' %}" rel="stylesheet">
    <link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/search.css' %}" rel="stylesheet">

    <script type="text/javascript" src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src="{% static 'bootstrap/js/bootstrap.js' %}"></script>
    <script type="text/javascript" src="{% static 'js/search.js' %}"></script>


    <!--[if lt IE 9]>
    <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->

</head>

<body>

<div class="navbar navbar-inverse navbar-fixed-top">
   <div class="container">
      <div class="navbar-header">
         <a class="navbar-brand" href="{% url 'interviews:index' %}">面经</a>
         <form id="form-search" class="navbar-form pull-left" role="search" method="get" action="{% url 'interviews:search'%}">
           <div class="form-group">
             <input type="text" name="wd" class="form-control search clearable" placeholder="{{ tips }}" value="{{ search_keyword }}">
             <i class="fa fa-search" id="i-search"></i>
           </div>
         </form>
      </div>

      <!--/.navbar-collapse -->
   </div>
</div>


<div>


    <div class="container">
        <div class="row">
            <div class="col-xs-12">
                <p>共为您找到{{ result_num }}个结果</p>
            </div>
        </div>
        <div class="row results">

            <div class="col-xs-12 col-md-8 content-wrapper">
            {% for item, tags in items %}
                <div class="content">
                    <a name="{{ forloop.counter }}" class="content-title" href="{{ item.link }}" target="_blank">{{ item.title }}</a>
                    {% for tag in tags %}
                    <span class="result-tag" onclick="javascript:httpGet('{% url 'interviews:search' %}', '{{ tag }}')">{{ tag }}</span>
                    {% endfor %}
                    <p>
                        <span class="content-time">{{ item.create_time }} - </span>
                        {% if item.description|length > 200 %}
                        <span hidden class="content-desc-all">{{ item.description}}</span>
                        <span class="content-desc-partial">{{ item.description|slice:"200" }} ...</span>
                        <a title="{{ forloop.counter }}" href="javascript:void(0);" class="toggle-expand" onclick="content_toggle(this)">Show All</a>
                        {% else %}
                        <span class="content-desc">{{ item.description }}</span>
                        {% endif %}
                    </p>
                    <div class="content-footer">
                        <a class="content-source" href="{{ item.source_link }}" target="_blank">{{ item.source }}</a>
                        &nbsp;&nbsp;&nbsp;
                        <a class="content-source" href="{{ item.link }}" target="_blank">查看原帖</a>
                    </div>
                </div>
            {% endfor %}

            {% if pages %}
                <ul class="pagination pagination">
                    {% if prev_page %}
                    <li class="prev">
                        <a rel="prev" href="{{ prev_page }}">← 上一页</a>
                    </li>
                    {% else %}
                    <li class="prev disabled">
                        <span>← 上一页</span>
                    </li>
                    {% endif %}

                    {% for page_id, page_url in pages %}

                        {% if page_id == current_page_num %}
                        <li class="active">
                            <a href="{{ page_url }}">{{ page_id }}</a>
                        </li>
                        {% else %}
                        <li>
                            <a href="{{ page_url }}">{{ page_id }}</a>
                        </li>
                        {% endif %}
                    {% endfor %}

                    {% if next_page %}
                    <li class="next">
                        <a rel="next" href="{{ next_page }}">下一页 →</a>
                    </li>
                    {% else %}
                    <li class="next disabled">
                        <span rel="next">下一页 →</span>
                    </li>
                    {% endif %}

                </ul>
            {% endif %}
                <p>
                    <small>
                        Displaying results
                        {% if item_start_id > item_end_id %}
                        0
                        {% else %}
                        <b>{{ item_start_id }}&nbsp;-&nbsp;{{ item_end_id }}</b>
                        {% endif %}
                        of <b>{{ result_num }}</b> in total
{#                        -#}
{#                        <a class="rss" href="/search.atom?order=desc&amp;page=1&amp;q=s&amp;sort=created_at">#}
{#                            <i class="fa fa-rss-square"></i>#}
{#                            Subscribe to an RSS feed of this search#}
{#                        </a>#}
                    </small>
                </p>

            </div>

        </div> <!-- / row -->
    </div>


{#<div id="page">#}
{##}
{#    {% if prev_page %}#}
{#    <a href="{{ prev_page }}" class="n">&lt;上一页</a>#}
{#    {% endif %}#}
{##}
{#    {% for page_id, page_url in pages %}#}
{##}
{#        {% if page_id == current_page_num %}#}
{#            <strong>#}
{#                <span class="pc">{{ page_id }}</span>#}
{#            </strong>#}
{#        {% else %}#}
{#            <a href="{{ page_url }}">#}
{#                <span class="pc">{{ page_id }}</span>#}
{#            </a>#}
{#        {% endif %}#}
{#    {% endfor %}#}
{##}
{#    {% if next_page %}#}
{#    <a href="{{ next_page }}" class="n">下一页&gt;</a>#}
{#    {% endif %}#}
{#</div>#}

</div>



</body>

</html>